export const EDUCATION_DETAILS = 'EDUCATION_DETAILS'
export const KEY_SKILLS_DETAILS = "KEY_SKILLS_DETAILS";
export const PERSONAL_INFO_VALUE = 'PERSONAL_INFO_VALUE'
export const PROFILE_INFO_VALUE = 'PROFILE_INFO_VALUE'
export const SET_TEMPLATE = "SET_TEMPLATE";

export const REMOVE_RESUME_TEMPLATES = "REMOVE_RESUME_TEMPLATES";
export const WORK_EXPERIENCE = "WORK_EXPERIENCE";
